/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MdStockPrice {
    }
}
declare global {
    interface HTMLMdStockPriceElement extends Components.MdStockPrice, HTMLStencilElement {
    }
    var HTMLMdStockPriceElement: {
        prototype: HTMLMdStockPriceElement;
        new (): HTMLMdStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "md-stock-price": HTMLMdStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface MdStockPrice {
    }
    interface IntrinsicElements {
        "md-stock-price": MdStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "md-stock-price": LocalJSX.MdStockPrice & JSXBase.HTMLAttributes<HTMLMdStockPriceElement>;
        }
    }
}
